use crate::common::*;

use codegen_writer::g;
use codegen_writer::glines;

pub fn codegen() {
    glines![
        "// Auto generated by codegen/src/api.rs"
        ""
        "use crate::extra::{Result, Base64Options, LastChunkHandlingOptions};"
        ""
    ];

    codegen_validate();
    codegen_count();
    codegen_transcoding_length();
    codegen_transcoding_convert();
    codegen_base64();
}

fn decl_ne_and_bom(encoding: &str) {
    if matches!(encoding, "utf16" | "utf32") {
        g!("/// This function uses native endianness.");
        g!("///");
    }

    if encoding.starts_with("utf16") {
        g!("/// This function is not BOM-aware.");
        g!("///");
    }
}

fn decl_assume(encoding: &str) {
    let doc_name = map_doc_name(encoding);
    g!("/// + The input string must be valid {doc_name}.");
}

fn decl_src_dst(from_encoding: &str, to_encoding: &str) {
    let from_ch_ty = map_rs_char_type(from_encoding);
    let to_ch_ty = map_rs_char_type(to_encoding);
    decl_src_dst_tys(from_ch_ty, to_ch_ty, "src", "dst");
}

fn decl_src_dst_tys(from_ch_ty: &str, to_ch_ty: &str, from_name: &str, to_name: &str) {
    g!("/// + `{from_name}` and `{to_name}` must be non-null and properly aligned.");
    g!("/// + `{from_name}` must be valid for reads of `len * size_of::<{from_ch_ty}>()` bytes");
    g!("/// + `{to_name}` must be valid for writes of `count * size_of::<{to_ch_ty}>()` bytes, \
        where the `count` is the number of code units ([`{to_ch_ty}`]) after successful conversion.");
    g!("/// + The memory regions of `{from_name}` and `{to_name}` must not overlap.");
    // TODO: inplace mode?
}

fn codegen_validate() {
    for_each_validate(|encoding| {
        let ch = map_rs_char_type(encoding);
        let doc_name = map_doc_name(encoding);

        g!("/// Validate the {doc_name} string.");
        g!("///");

        decl_ne_and_bom(encoding);

        g!("/// Returns [`true`] if and only if the string is valid {doc_name}.");

        g!("#[inline]");
        g!("#[must_use]");
        g!("pub fn validate_{encoding}(src: &[{ch}]) -> bool {{");
        g!("let len = src.len();");
        g!("let buf = src.as_ptr();");
        g!("unsafe {{ crate::bindings::simdutf_validate_{encoding}(buf, len) }}");
        g!("}}");
        g!();
    });

    for_each_validate(|encoding| {
        let ch = map_rs_char_type(encoding);
        let doc_name = map_doc_name(encoding);

        g!("/// Validate the {doc_name} string.");
        g!("///");

        decl_ne_and_bom(encoding);

        g!("#[inline]");
        g!("#[must_use]");
        g!("pub fn validate_{encoding}_with_errors(src: &[{ch}]) -> Result {{");
        g!("let len = src.len();");
        g!("let buf = src.as_ptr();");
        g!("unsafe {{ crate::bindings::simdutf_validate_{encoding}_with_errors(buf, len) }}");
        g!("}}");
        g!();
    });
}

fn codegen_count() {
    for_each_count(|encoding| {
        let ch = map_rs_char_type(encoding);
        let doc_name = map_doc_name(encoding);

        g!("/// Count the number of code points in the {doc_name} string.");
        g!("///");

        decl_ne_and_bom(encoding);

        g!("/// This function does not validate the input.");
        g!("/// It is acceptable to pass invalid {doc_name} strings but in such cases the result is implementation defined.");
        g!("///");

        g!("#[inline]");
        g!("#[must_use]");
        g!("pub fn count_{encoding}(src: &[{ch}]) -> usize {{");
        g!("let len = src.len();");
        g!("let buf = src.as_ptr();");
        g!("unsafe{{ crate::bindings::simdutf_count_{encoding}(buf, len) }}");
        g!("}}");
        g!();
    });
}

fn codegen_transcoding_length() {
    for_each_transcoding_length(|from, to| {
        if from == "latin1" && to == "utf32" {
            return;
        }
        let from_ch = map_rs_char_type(from);
        let from_doc_name = map_doc_name(from);
        let to_doc_name = map_doc_name(to);

        g!("/// Count the number of code units that \
             the {from_doc_name} string would require in {to_doc_name} format.");
        g!("///");

        if to == "utf32" {
            g!("/// This function is equivalent to [`count_{from}`].");
            g!("///");
        }

        decl_ne_and_bom(from);

        g!("/// This function does not validate the input.");
        g!("/// It is acceptable to pass invalid {from_doc_name} strings but in such cases the result is implementation defined.");
        g!("///");

        g!("#[inline]");
        g!("#[must_use]");
        if is_fixed_length_for_latin1(from, to) {
            g!("pub fn {to}_length_from_{from}(src_len: usize) -> usize {{");
            g!("    unsafe{{ crate::bindings::simdutf_{to}_length_from_{from}(src_len) }}");
            g!("}}");
        } else {
            g!("pub fn {to}_length_from_{from}(src: &[{from_ch}]) -> usize {{");
            g!("    let len = src.len();");
            g!("    let buf = src.as_ptr();");
            g!("    unsafe{{ crate::bindings::simdutf_{to}_length_from_{from}(buf, len) }}");
            g!("}}");
        }
        g!();
    })
}

fn codegen_transcoding_convert() {
    for_each_transcoding_convert(|from, to| {
        let from_ch = map_rs_char_type(from);
        let to_ch = map_rs_char_type(to);
        let from_doc_name = map_doc_name(from);
        let to_doc_name = map_doc_name(to);

        g!("/// Convert possibly broken {from_doc_name} string into {to_doc_name} string.");
        g!("///");
        g!("/// During the conversion also validation of the input string is done.");
        g!("/// This function is suitable to work with inputs from untrusted sources.");
        g!("///");
        g!("/// Returns the number of written code units; \
            0 if the input is not a valid {from_doc_name} string");
        g!("///");

        decl_ne_and_bom(from);

        g!("/// # Safety");
        decl_src_dst(from, to);

        g!("#[inline]");
        g!("#[must_use]");
        g!("pub unsafe fn convert_{from}_to_{to}\
            (src: *const {from_ch}, len: usize, dst: *mut {to_ch}) -> usize {{");
        g!("crate::bindings::simdutf_convert_{from}_to_{to}(src, len, dst)");
        g!("}}");
        g!();
    });

    for_each_transcoding_convert(|from, to| {
        if from == "latin1" || (from == "utf32" && to == "latin1") {
            return;
        }
        let from_ch = map_rs_char_type(from);
        let to_ch = map_rs_char_type(to);
        let from_doc_name = map_doc_name(from);
        let to_doc_name = map_doc_name(to);

        g!("/// Convert possibly broken {from_doc_name} string into {to_doc_name} string.");
        g!("///");
        g!("/// During the conversion also validation of the input string is done.");
        g!("/// This function is suitable to work with inputs from untrusted sources.");
        g!("///");

        decl_ne_and_bom(from);

        g!("/// # Safety");
        decl_src_dst(from, to);

        g!("#[inline]");
        g!("#[must_use]");
        g!("pub unsafe fn convert_{from}_to_{to}_with_errors\
            (src: *const {from_ch}, len: usize, dst: *mut {to_ch}) -> Result {{");
        g!("crate::bindings::simdutf_convert_{from}_to_{to}_with_errors(src, len, dst)");
        g!("}}");
        g!();
    });

    for_each_transcoding_convert(|from, to| {
        if from == "latin1" || (from == "utf32" && to == "latin1") {
            return;
        }
        let from_ch = map_rs_char_type(from);
        let to_ch = map_rs_char_type(to);
        let from_doc_name = map_doc_name(from);
        let to_doc_name = map_doc_name(to);

        g!("/// Convert valid {from_doc_name} string into {to_doc_name} string.");
        g!("///");
        g!("/// Returns the number of written code units.");
        g!("///");

        decl_ne_and_bom(from);

        g!("/// # Safety");
        decl_assume(from);
        decl_src_dst(from, to);

        g!("#[inline]");
        g!("#[must_use]");
        g!("pub unsafe fn convert_valid_{from}_to_{to}\
            (src: *const {from_ch}, len: usize, dst: *mut {to_ch}) -> usize {{");
        g!("crate::bindings::simdutf_convert_valid_{from}_to_{to}(src, len, dst)");
        g!("}}");
        g!();
    })
}

fn codegen_base64() {
    g!("/// Convert base64 string into binary data.");
    g!("///");
    g!("/// # Safety");
    decl_src_dst_tys("u8", "u8", "input", "output");
    g!("#[inline]");
    g!("#[must_use]");
    g!("pub unsafe fn base64_to_binary_safe(");
    g!("    input: *const u8,");
    g!("    len: usize,");
    g!("    output: *mut u8,");
    g!("    out_len: *mut usize,");
    g!("    options: Base64Options,");
    g!("    last_chunk_options: LastChunkHandlingOptions,");
    g!("    decode_up_to_bad_char: bool,");
    g!(") -> Result {{");
    g!("    crate::bindings::simdutf_base64_to_binary_safe(input, len, output, out_len, options as u64, last_chunk_options as u64, decode_up_to_bad_char)");
    g!("}}");
    g!();

    g!("/// Convert binary data into base64.");
    g!("///");
    g!("/// # Safety");
    decl_src_dst_tys("u8", "u8", "input", "output");
    g!("#[inline]");
    g!("#[must_use]");
    g!("pub unsafe fn binary_to_base64(");
    g!("    input: *const u8,");
    g!("    len: usize,");
    g!("    output: *mut u8,");
    g!("    options: Base64Options,");
    g!(") -> usize {{");
    g!("    crate::bindings::simdutf_binary_to_base64(input, len, output, options as u64)");
    g!("}}");
}
