use crate::common::*;
use crate::gen::Codegen;

use std::format as f;

pub fn codegen(g: &mut Codegen) {
    g.lines([
        "// Auto generated by codegen/src/bindings.rs", //
        "extern \"C\" {",
        "",
    ]);

    for encoding in ENCODINGS {
        let ch = map_rs_char_type(encoding);
        g.ln(f!("pub fn simdutf_validate_{encoding}(buf: *const {ch}, len: usize) -> bool;"));
        g.lf();
    }

    g.ln("}");
}
