use crate::common::*;
use crate::gen::Codegen;

use std::format as f;

pub fn codegen(g: &mut Codegen) {
    g.lines([
        "// Auto generated by codegen/src/cpp.rs",
        "#include \"simdutf.cpp\"",
        "",
        "extern \"C\" {",
        "",
    ]);

    for encoding in ENCODINGS {
        let ch = map_cpp_char_type(encoding);
        g.ln(f!("bool simdutf_validate_{encoding}(const {ch}* buf, size_t len) {{"));
        g.ln(f!("    return simdutf::validate_{encoding}(buf, len);"));
        g.ln("}");
        g.lf();
    }

    g.ln("}");
}
