// Auto generated by codegen/src/cpp.rs
#include "simdutf.cpp"

extern "C" {

bool simdutf_validate_ascii(const char *buf, size_t len) {
    return simdutf::validate_ascii(buf, len);
}

bool simdutf_validate_utf8(const char *buf, size_t len) {
    return simdutf::validate_utf8(buf, len);
}

bool simdutf_validate_utf16(const char16_t *buf, size_t len) {
    return simdutf::validate_utf16(buf, len);
}

bool simdutf_validate_utf16be(const char16_t *buf, size_t len) {
    return simdutf::validate_utf16be(buf, len);
}

bool simdutf_validate_utf16le(const char16_t *buf, size_t len) {
    return simdutf::validate_utf16le(buf, len);
}

bool simdutf_validate_utf32(const char32_t *buf, size_t len) {
    return simdutf::validate_utf32(buf, len);
}
}
