// Auto generated by codegen/src/bindings.rs
#include "simdutf.cpp"
#include "simdutfrs_extra.cpp"

extern "C" {

simdutfrs_result_t simdutfrs_validate_ascii_with_errors(const char *buf,
                                                        size_t len) {
    const simdutf::result ans = simdutf::validate_ascii_with_errors(buf, len);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_validate_utf8_with_errors(const char *buf,
                                                       size_t len) {
    const simdutf::result ans = simdutf::validate_utf8_with_errors(buf, len);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_validate_utf16_with_errors(const char16_t *buf,
                                                        size_t len) {
    const simdutf::result ans = simdutf::validate_utf16_with_errors(buf, len);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_validate_utf16be_with_errors(const char16_t *buf,
                                                          size_t len) {
    const simdutf::result ans = simdutf::validate_utf16be_with_errors(buf, len);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_validate_utf16le_with_errors(const char16_t *buf,
                                                          size_t len) {
    const simdutf::result ans = simdutf::validate_utf16le_with_errors(buf, len);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_validate_utf32_with_errors(const char32_t *buf,
                                                        size_t len) {
    const simdutf::result ans = simdutf::validate_utf32_with_errors(buf, len);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_convert_utf8_to_utf16_with_errors(const char *src,
                                                               size_t len,
                                                               char16_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf8_to_utf16_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf8_to_utf16be_with_errors(const char *src, size_t len,
                                              char16_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf8_to_utf16be_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf8_to_utf16le_with_errors(const char *src, size_t len,
                                              char16_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf8_to_utf16le_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_convert_utf8_to_utf32_with_errors(const char *src,
                                                               size_t len,
                                                               char32_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf8_to_utf32_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_convert_utf8_to_latin1_with_errors(const char *src,
                                                                size_t len,
                                                                char *dst) {
    const simdutf::result ans =
        simdutf::convert_utf8_to_latin1_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16_to_utf8_with_errors(const char16_t *src, size_t len,
                                            char *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16_to_utf8_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16_to_utf32_with_errors(const char16_t *src, size_t len,
                                             char32_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16_to_utf32_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16_to_latin1_with_errors(const char16_t *src, size_t len,
                                              char *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16_to_latin1_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16be_to_utf8_with_errors(const char16_t *src, size_t len,
                                              char *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16be_to_utf8_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16be_to_utf32_with_errors(const char16_t *src, size_t len,
                                               char32_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16be_to_utf32_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16be_to_latin1_with_errors(const char16_t *src, size_t len,
                                                char *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16be_to_latin1_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16le_to_utf8_with_errors(const char16_t *src, size_t len,
                                              char *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16le_to_utf8_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16le_to_utf32_with_errors(const char16_t *src, size_t len,
                                               char32_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16le_to_utf32_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf16le_to_latin1_with_errors(const char16_t *src, size_t len,
                                                char *dst) {
    const simdutf::result ans =
        simdutf::convert_utf16le_to_latin1_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf32_to_utf8_with_errors(const char32_t *src, size_t len,
                                            char *dst) {
    const simdutf::result ans =
        simdutf::convert_utf32_to_utf8_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf32_to_utf16_with_errors(const char32_t *src, size_t len,
                                             char16_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf32_to_utf16_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf32_to_utf16be_with_errors(const char32_t *src, size_t len,
                                               char16_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf32_to_utf16be_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t
simdutfrs_convert_utf32_to_utf16le_with_errors(const char32_t *src, size_t len,
                                               char16_t *dst) {
    const simdutf::result ans =
        simdutf::convert_utf32_to_utf16le_with_errors(src, len, dst);
    return {static_cast<uint32_t>(ans.error), ans.count};
}

simdutfrs_result_t simdutfrs_base64_to_binary_safe(const char *input,
                                                   size_t length, char *output,
                                                   size_t *outlen,
                                                   uint64_t options) {
    const simdutf::result res = simdutf::base64_to_binary_safe(
        input, length, output, *outlen,
        static_cast<simdutf::base64_options>(options));
    return {static_cast<uint32_t>(res.error), res.count};
}

size_t simdutfrs_binary_to_base64(const char *input, size_t length,
                                  char *output, uint64_t options) {
    return simdutf::binary_to_base64(
        input, length, output, static_cast<simdutf::base64_options>(options));
}
}
