[package]
name = "simdutf-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.codegen-tools]
git = "https://github.com/Nugine/codegen-tools"
rev = "284bd050b9fb763509c3faf7af23b928dea1aea3"
