on:
  schedule:
    - cron: '0 0 * * 0' # at midnight of each sunday
  workflow_dispatch:

name: Upgrade

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name  "github-actions[bot]"
      - run: pip3 install requests typer
      - run: ./scripts/upgrade.py upgrade --pr
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
